spring.application.name=gift
spring.datasource.url=jdbc:postgresql://dpg-d2htf63uibrs73dl5d3g-a.oregon-postgres.render.com:5432/giftpg?sslmode=require
spring.datasource.username=postgres_user
spring.datasource.password=iK8SiOQuX0DoHDBWypC5szGASgYobxyL
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update   # (create, update, validate, none)
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
